apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 200.58.106.200
      user: root
      port: 22
      keyPath: null
    role: controller
  - ssh:
      address: 200.58.106.200
      user: root
      port: 2222  # Puerto SSH externo para el host trabajador
      keyPath: null
    role: worker
  k0s:
    version: 1.27.2+k0s.0
    dynamicConfig: false


